### ISSUE TITLE
Can you release the code file of your attention map?

### ISSUE THREAD

**Issue by zhongqiu1245** [ZjjConan/SimAM#1]
Hi, dear author!
Sorry to bother you.
Could you release the *.py of your visualized neuron(attention map/heatmap)?
Thank you!

**Comment by ZjjConan** [comment]
Sorry，I didn't retain such code for visualization. In fact, I show the heatmap (attention or feature map) via gradcam, which can be found here (https://github.com/kazuto1011/grad-cam-pytorch). Hope it can help you
