### ISSUE TITLE
关于mmdetection训练日志log中的一些疑惑

### ISSUE THREAD

**Issue by WYHZQ** [ZjjConan/SimAM#17]
亲爱的作者您好，最近在查看您在百度云发布的mmdetection日志文件时产生了一些疑惑，望您解答。
下图是在您的百度云中下载的Mask RCNN Res50 的日志片段。如图所示，当验证集为coco2017val时，其总图片为5000，采用四卡验证应该显示数目为**1250**，但是您的训练日志验证时却显示的和训练时一样为**14659**。疑惑是否是实验设置时误把训练集也当作验证集了呢。

![捕获](https://user-images.githubusercontent.com/75660358/170165870-4c22665b-7802-45e2-a9bf-ba13eca129b2.JPG)

**Comment by ZjjConan** [comment]
您好，实际上我并没更改数据部分的 config，可参考下图：
![image](https://user-images.githubusercontent.com/4981172/170171682-7f54e145-ebf5-4b92-ae76-90f10aded141.png)

另外，可参考 https://github.com/SwinTransformer/Swin-Transformer-Object-Detection，这也提供了log参考，他应该是8GPUs训练，val 部分iter的显示为7330。

实际上这一部分只是显示上的问题，可参考mmdetection官方公布log，val的显示也与这里不同。如果实在怀疑，可利用mmdetection把提供的训练好的模型在测试集上跑一遍就可以了。

希望回答能够帮到您。

**Comment by WYHZQ** [comment]
好的，感谢您的耐心解答，收获颇丰。

> 您好，实际上我并没更改数据部分的 config，可参考下图： ![图片](https://user-images.githubusercontent.com/4981172/170171682-7f54e145-ebf5-4b92-ae76-90f10aded141.png)
> 
> 另外，可参考 [https://github.com/SwinTransformer/Swin-Transformer-Object-Detection ](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection) 这也提供了log参考，他应该是8GPUs训练，val 部分iter的显示为7330。
> 
> 实际上这一部分只是显示上的问题，可参考mmdetection官方公布log，val的显示也与这里不同。如果实在怀疑，可利用mmdetection把提供的训练好的模型在测试集上跑一遍就可以了。
> 
> 希望回答能够帮到您。

好的，感谢您的耐心解答，收获颇丰
