### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by WYC77** [ZjjConan/SimAM#18]
你好，我在github中打不开预训练模型，您是否能够提供一下SimAM-R50预训练模型呢

**Comment by ZjjConan** [comment]
百度网盘的链接已经更新，但是百度网盘一直都不是很稳定，如果OK，建议用VPN去Google Drvier上下载

**Comment by WYC77** [comment]
非常感谢您的回复，现在已经能下载了。




3058169233
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZjjConan/SimAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月8日(星期六) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZjjConan/SimAM] 预训练模型 (Issue #18)





 
百度网盘的链接已经更新，但是百度网盘一直都不是很稳定，如果OK，建议用VPN去Google Drvier上下载
