### ISSUE TITLE
关于实现的问题

### ISSUE THREAD

**Issue by guozhiyao** [ZjjConan/SimAM#4]
你好，论文中的公式5为了减少每个位置的重复计算，简化为使用所有神经元上的均值和方差，但是在实现代码中，方差除以了`H*W-1`。

https://github.com/ZjjConan/SimAM/blob/a6ee6719a2bd7280020156b47154fd3c73c87258/networks/attentions/simam_module.py#L25

**Comment by ZjjConan** [comment]
Hi, @guozhiyao，您好，准确来说应该是 (x - mu).pow(2).sum / n来求得方差，并非是方差除以HW-1. 如果是用hw求方差则是bias的方差，hw-1则是unbias的方差。希望能帮到您。

**Comment by guozhiyao** [comment]
谢谢你的解答。此外，我发现能量值1/E应该是一个大于0的数，通过sigmoid对其放缩只会得到(0.5, 1)的值，而不是(0, 1)，这会不会限制了attention的性能？

**Comment by guozhiyao** [comment]
论文中Figure 6的可视化结果，你们是直接可视化计算出来的sigmoid(1/E)吗？

**Comment by guozhiyao** [comment]
@ZjjConan

**Comment by ZjjConan** [comment]
@guozhiyao 论文通过gradcam来进行显示

**Comment by sxin1** [comment]
> 你好，论文中的公式5为了减少每个位置的重复计算，简化为使用所有神经元上的均值和方差，但是在实现代码中，方差除以了`H*W-1`。
> 
> https://github.com/ZjjConan/SimAM/blob/a6ee6719a2bd7280020156b47154fd3c73c87258/networks/attentions/simam_module.py#L25

您好,我在推倒公式5的过程中遇到了问题,请问公式5是怎么推导出来的呢
