### ISSUE TITLE
Hello: This work is very interesting. The article is well-founded. I manually derived the formula in the paper and found that the expression of δ²_t in the paper seems to be problematic.

### ISSUE THREAD

**Issue by Suke0** [ZjjConan/SimAM#6]
δ²_t is not equal to 1/(M-1) * ∑(x_i - u_t)², 
it is equal to 1/(M-1) * ∑(x²_i - u²_t).

**Comment by ZjjConan** [comment]
@Suke0, Thanks for your attention. Actually, you can expand (*) in the first equation.

**Comment by Suke0** [comment]
ok，I’ve got it。think you。

**Comment by Ema1997** [comment]
> @Suke0, Thanks for your attention. Actually, you can expand (*) in the first equation.

There will still be a 2u_t x_i when expanding the first equation, so the two equations are still unequal? @ZjjConan @Suke0

**Comment by Suke0** [comment]
They are equal. You should calculate more carefully.

**Comment by Ema1997** [comment]
> They are equal. You should calculate more carefully.

Ok, I got it. Thanks.
